### PR TITLE
delete CR from varvalue

### PR DESCRIPTION
**Pull request by hmassad**

### CODE REVIEW

**Comment by kunokdev** [comment]
Hey sorry for inactivity and thanks for noticing this;
I merged other PR with improvements. (https://github.com/kunokdev/cra-runtime-environment-variables/pull/9)
@hmassad Would you like to check if this is still the issue and rebase?

**Comment by hmassad** [comment]
unfortunately the awk version doesn't handle CRLF line endings
I'll try fo find a fix, I need to learn some awk

**Comment by kunokdev** [comment]
> unfortunately the awk version doesn't handle CRLF line endings
> I'll try fo find a fix, I need to learn some awk

Alright, cool, let me know!

**Comment by kunokdev** [comment]
Closing due to inactivity. Feel free to reopen this PR when progress is made.

**Pull request closed without merging**
